name: shop_sim
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  awesome_dialog: ^3.2.1
  flutter:
    sdk: flutter
  pastel_theme_package:
    path: ../pastel_theme_package
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
